"use client";

import { useEffect, useRef } from "react";

interface DocContent {
  [key: string]: any;
}

interface Document {
  id: number;
  name: string;
  date: string;
  type: string;
  pages: number;
  content: DocContent;
}

interface Props {
  doc: Document;
  patientName: string;
  onClose: () => void;
}

const fmtDate = (iso: string) =>
  new Date(iso).toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric",
  });

const TYPE_COLORS: Record<string, string> = {
  Discharge:   "#3b82f6",
  Insurance:   "#10b981",
  Vaccination: "#8b5cf6",
};

// ── Build downloadable text per document type ─────────────────────────────────
function buildTextContent(doc: Document, patientName: string): string {
  const sep = "=".repeat(60);
  const sub = "-".repeat(60);
  const c   = doc.content;

  const header = [
    sep,
    "          SHEDULA HEALTH — PATIENT DOCUMENT",
    sep,
    `Document : ${doc.name}`,
    `Patient  : ${patientName}`,
    `Date     : ${fmtDate(doc.date)}`,
    `Type     : ${doc.type}`,
    "",
  ];

  let body: string[] = [];

  if (doc.type === "Discharge") {
    body = [
      sub, "DISCHARGE SUMMARY", sub,
      `Hospital         : ${c.hospital}`,
      `Date of Admission: ${fmtDate(c.admissionDate)}`,
      `Date of Discharge: ${fmtDate(c.dischargeDate)}`,
      `Diagnosis        : ${c.diagnosis}`,
      "",
      "Treatment:",
      c.treatment,
      "",
      sub, "MEDICATIONS AT DISCHARGE", sub,
      ...(c.medications as any[]).map(
        (m: any) => `  • ${m.name} — ${m.instruction}`
      ),
      "",
      `Follow-up: ${c.followUp}`,
    ];
  } else if (doc.type === "Insurance") {
    body = [
      sub, "INSURANCE DETAILS", sub,
      `Provider         : ${c.provider}`,
      `Policy Number    : ${c.policyNo}`,
      `Insured Name     : ${c.insuredName}`,
      `Sum Insured      : ${c.sumInsured}`,
      `Valid From       : ${c.validFrom}`,
      `Valid To         : ${c.validTo}`,
      `TPA              : ${c.tpaName}`,
      `Emergency No     : ${c.emergencyNo}`,
      `Network Hospitals: ${c.networkHospitals}`,
    ];
  } else if (doc.type === "Vaccination") {
    body = [
      sub, "VACCINATION CERTIFICATE", sub,
      `Vaccine          : ${c.vaccine}`,
      `Beneficiary      : ${c.beneficiaryName}`,
      `Date of Birth    : ${c.dob}`,
      "",
      `Dose 1 Date      : ${fmtDate(c.dose1Date)}`,
      `Dose 1 Batch     : ${c.dose1Batch}`,
      `Dose 1 Site      : ${c.dose1Site}`,
      "",
      `Dose 2 Date      : ${fmtDate(c.dose2Date)}`,
      `Dose 2 Batch     : ${c.dose2Batch}`,
      `Dose 2 Site      : ${c.dose2Site}`,
      "",
      `Booster Date     : ${fmtDate(c.boosterDate)}`,
      `Booster Batch    : ${c.boosterBatch}`,
      `Booster Site     : ${c.boosterSite}`,
      "",
      `Certificate No   : ${c.certificateNo}`,
    ];
  }

  return [
    ...header,
    ...body,
    "",
    sep,
    "* Sample document generated by Shedula Health Demo *",
    sep,
  ].join("\n");
}

function downloadDoc(doc: Document, patientName: string) {
  const text = buildTextContent(doc, patientName);
  const blob = new Blob([text], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `${doc.name.replace(/[^a-zA-Z0-9]/g, "_")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Renderers per doc type ────────────────────────────────────────────────────
function DischargeContent({ c }: { c: DocContent }) {
  return (
    <div className="dvm-content">
      <div className="dvm-kv-grid">
        {[
          ["Hospital",          c.hospital],
          ["Date of Admission", fmtDate(c.admissionDate)],
          ["Date of Discharge", fmtDate(c.dischargeDate)],
          ["Diagnosis",         c.diagnosis],
        ].map(([k, v]) => (
          <div key={k} className="dvm-kv">
            <span className="dvm-kv__label">{k}</span>
            <span className="dvm-kv__value">{v}</span>
          </div>
        ))}
      </div>

      <div className="dvm-section">
        <div className="dvm-section__label">Treatment Summary</div>
        <p className="dvm-para">{c.treatment}</p>
      </div>

      <div className="dvm-section">
        <div className="dvm-section__label">Medications at Discharge</div>
        <div className="dvm-med-list">
          {(c.medications as any[]).map((m: any, i: number) => (
            <div key={i} className="dvm-med-item">
              <div className="dvm-med-item__dot" />
              <div>
                <span className="dvm-med-item__name">{m.name}</span>
                <span className="dvm-med-item__instr">{m.instruction}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="dvm-followup">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
          <rect x="3" y="4" width="18" height="18" rx="2"
            stroke="currentColor" strokeWidth="1.8" />
          <path d="M16 2v4M8 2v4M3 10h18"
            stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
        </svg>
        <span>Follow-up: <strong>{c.followUp}</strong></span>
      </div>
    </div>
  );
}

function InsuranceContent({ c, patientName }: { c: DocContent; patientName: string }) {
  return (
    <div className="dvm-content">
      <div className="dvm-insurance-card">
        <div className="dvm-insurance-card__header">
          <span className="dvm-insurance-card__provider">{c.provider}</span>
          <span className="dvm-insurance-card__logo">★ Star Health</span>
        </div>
        <div className="dvm-insurance-card__name">{c.insuredName}</div>
        <div className="dvm-insurance-card__policy">Policy: {c.policyNo}</div>
        <div className="dvm-insurance-card__row">
          <div>
            <span className="dvm-insurance-card__lbl">Sum Insured</span>
            <span className="dvm-insurance-card__val">{c.sumInsured}</span>
          </div>
          <div>
            <span className="dvm-insurance-card__lbl">Valid Until</span>
            <span className="dvm-insurance-card__val">{c.validTo}</span>
          </div>
        </div>
      </div>

      <div className="dvm-kv-grid">
        {[
          ["TPA",                c.tpaName],
          ["Emergency Helpline", c.emergencyNo],
          ["Network Hospitals",  c.networkHospitals],
          ["Valid From",         c.validFrom],
          ["Valid To",           c.validTo],
        ].map(([k, v]) => (
          <div key={k} className="dvm-kv">
            <span className="dvm-kv__label">{k}</span>
            <span className="dvm-kv__value">{v}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function VaccinationContent({ c }: { c: DocContent }) {
  const doses = [
    { label: "Dose 1", date: c.dose1Date, batch: c.dose1Batch, site: c.dose1Site },
    { label: "Dose 2", date: c.dose2Date, batch: c.dose2Batch, site: c.dose2Site },
    { label: "Booster", date: c.boosterDate, batch: c.boosterBatch, site: c.boosterSite },
  ];

  return (
    <div className="dvm-content">
      <div className="dvm-vacc-badge">
        <div className="dvm-vacc-badge__icon">
          <svg width="28" height="28" viewBox="0 0 24 24" fill="none">
            <path d="M9 12l2 2 4-4M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              stroke="currentColor" strokeWidth="1.8"
              strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </div>
        <div>
          <div className="dvm-vacc-badge__title">
            Fully Vaccinated &amp; Boosted
          </div>
          <div className="dvm-vacc-badge__sub">{c.vaccine}</div>
        </div>
      </div>

      <div className="dvm-kv-grid">
        {[
          ["Beneficiary",     c.beneficiaryName],
          ["Date of Birth",   c.dob],
          ["Certificate No",  c.certificateNo],
        ].map(([k, v]) => (
          <div key={k} className="dvm-kv">
            <span className="dvm-kv__label">{k}</span>
            <span className="dvm-kv__value">{v}</span>
          </div>
        ))}
      </div>

      <div className="dvm-section">
        <div className="dvm-section__label">Vaccination Timeline</div>
        <div className="dvm-timeline">
          {doses.map((d, i) => (
            <div key={i} className="dvm-timeline__item">
              <div className="dvm-timeline__dot">
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none">
                  <path d="M9 12l2 2 4-4" stroke="currentColor"
                    strokeWidth="2.5" strokeLinecap="round"
                    strokeLinejoin="round" />
                </svg>
              </div>
              {i < doses.length - 1 && <div className="dvm-timeline__line" />}
              <div className="dvm-timeline__body">
                <span className="dvm-timeline__label">{d.label}</span>
                <span className="dvm-timeline__date">{fmtDate(d.date)}</span>
                <span className="dvm-timeline__site">{d.site}</span>
                <span className="dvm-timeline__batch">Batch: {d.batch}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ── Main Modal ────────────────────────────────────────────────────────────────
export default function DocumentViewerModal({ doc, patientName, onClose }: Props) {
  const backdropRef = useRef<HTMLDivElement>(null);
  const color = TYPE_COLORS[doc.type] ?? "#6366f1";

  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, [onClose]);

  useEffect(() => {
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = ""; };
  }, []);

  return (
    <div
      className="rvm-backdrop"
      ref={backdropRef}
      onClick={(e) => { if (e.target === backdropRef.current) onClose(); }}
    >
      <div className="rvm-modal" role="dialog" aria-label={doc.name}>

        {/* ── Header ── */}
        <div className="rvm-header">
          <div className="rvm-header__left">
            <div className="rvm-header__icon"
              style={{ background: `${color}18`, color }}>
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
                <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6z"
                  stroke="currentColor" strokeWidth="1.8"
                  strokeLinecap="round" strokeLinejoin="round" />
                <path d="M14 2v6h6" stroke="currentColor"
                  strokeWidth="1.8" strokeLinecap="round" />
              </svg>
            </div>
            <div>
              <h2 className="rvm-header__title">{doc.name}</h2>
              <p className="rvm-header__sub">
                {doc.type} · {fmtDate(doc.date)} · {doc.pages} page{doc.pages > 1 ? "s" : ""}
              </p>
            </div>
          </div>
          <div className="rvm-header__right">
            <span className="rvm-status"
              style={{ background: `${color}15`, color, borderColor: `${color}40` }}>
              {doc.type}
            </span>
            <button
              className="rvm-btn rvm-btn--outline"
              onClick={() => downloadDoc(doc, patientName)}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3"
                  stroke="currentColor" strokeWidth="2"
                  strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Download
            </button>
            <button className="rvm-close" onClick={onClose}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
                <path d="M18 6L6 18M6 6l12 12" stroke="currentColor"
                  strokeWidth="2.5" strokeLinecap="round" />
              </svg>
            </button>
          </div>
        </div>

        {/* ── Content ── */}
        <div className="rvm-scroll">
          {doc.type === "Discharge"   && <DischargeContent   c={doc.content} />}
          {doc.type === "Insurance"   && <InsuranceContent   c={doc.content} patientName={patientName} />}
          {doc.type === "Vaccination" && <VaccinationContent c={doc.content} />}

          <p className="rvm-disclaimer">
            * Sample document for demonstration purposes. Not a real medical record.
          </p>
        </div>
      </div>
    </div>
  );
}