"use client";

import { useEffect, useRef } from "react";

interface Finding {
  test: string;
  result: string;
  unit: string;
  range: string;
  flag: string;
}

interface Report {
  id: number;
  name: string;
  date: string;
  lab: string;
  status: string;
  findings: Finding[];
  doctorNote: string;
}

interface Props {
  report: Report;
  patientName: string;
  onClose: () => void;
}

const fmtDate = (iso: string) =>
  new Date(iso).toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric",
  });

// ── Generate a plain-text version and trigger browser download ────────────────
function downloadReport(report: Report, patientName: string) {
  const lines: string[] = [
    "=".repeat(60),
    "          SHEDULA HEALTH — LAB REPORT",
    "=".repeat(60),
    "",
    `Report   : ${report.name}`,
    `Patient  : ${patientName}`,
    `Lab      : ${report.lab}`,
    `Date     : ${fmtDate(report.date)}`,
    `Status   : ${report.status}`,
    "",
    "-".repeat(60),
    "TEST FINDINGS",
    "-".repeat(60),
    `${"Test".padEnd(28)}${"Result".padEnd(12)}${"Unit".padEnd(12)}${"Range".padEnd(16)}Flag`,
    "-".repeat(60),
    ...report.findings.map((f) =>
      `${f.test.padEnd(28)}${f.result.padEnd(12)}${f.unit.padEnd(12)}${f.range.padEnd(16)}${f.flag || "—"}`
    ),
    "",
    "-".repeat(60),
    "DOCTOR'S NOTE",
    "-".repeat(60),
    report.doctorNote,
    "",
    "=".repeat(60),
    "* This is a sample report generated by Shedula Health Demo *",
    "=".repeat(60),
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `${report.name.replace(/\s+/g, "_")}_${report.date}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ReportViewerModal({ report, patientName, onClose }: Props) {
  const backdropRef = useRef<HTMLDivElement>(null);

  // Close on Escape
  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, [onClose]);

  // Prevent body scroll
  useEffect(() => {
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = ""; };
  }, []);

  const statusClass =
    report.status === "Normal" ? "rvm-status--green"
    : report.status === "Review" ? "rvm-status--amber"
    : "rvm-status--red";

  return (
    <div
      className="rvm-backdrop"
      ref={backdropRef}
      onClick={(e) => { if (e.target === backdropRef.current) onClose(); }}
    >
      <div className="rvm-modal" role="dialog" aria-label={report.name}>

        {/* ── Header ── */}
        <div className="rvm-header">
          <div className="rvm-header__left">
            <div className="rvm-header__icon">
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
                <path d="M9 14l2 2 4-4M7 3h10a2 2 0 012 2v14a2 2 0 01-2
                  2H7a2 2 0 01-2-2V5a2 2 0 012-2z"
                  stroke="currentColor" strokeWidth="1.8"
                  strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </div>
            <div>
              <h2 className="rvm-header__title">{report.name}</h2>
              <p className="rvm-header__sub">{report.lab} · {fmtDate(report.date)}</p>
            </div>
          </div>
          <div className="rvm-header__right">
            <span className={`rvm-status ${statusClass}`}>{report.status}</span>
            <button
              className="rvm-btn rvm-btn--outline"
              onClick={() => downloadReport(report, patientName)}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4
                  M7 10l5 5 5-5M12 15V3"
                  stroke="currentColor" strokeWidth="2"
                  strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Download
            </button>
            <button className="rvm-close" onClick={onClose} aria-label="Close">
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
                <path d="M18 6L6 18M6 6l12 12" stroke="currentColor"
                  strokeWidth="2.5" strokeLinecap="round" />
              </svg>
            </button>
          </div>
        </div>

        {/* ── Patient info strip ── */}
        <div className="rvm-patient-strip">
          <div className="rvm-patient-strip__item">
            <span>Patient</span>
            <strong>{patientName}</strong>
          </div>
          <div className="rvm-patient-strip__divider" />
          <div className="rvm-patient-strip__item">
            <span>Collected</span>
            <strong>{fmtDate(report.date)}</strong>
          </div>
          <div className="rvm-patient-strip__divider" />
          <div className="rvm-patient-strip__item">
            <span>Laboratory</span>
            <strong>{report.lab}</strong>
          </div>
          <div className="rvm-patient-strip__divider" />
          <div className="rvm-patient-strip__item">
            <span>Report ID</span>
            <strong>RPT-{report.id.toString().padStart(6, "0")}</strong>
          </div>
        </div>

        {/* ── Findings table ── */}
        <div className="rvm-scroll">
          <div className="rvm-section-title">Test Findings</div>

          <div className="rvm-table">
            <div className="rvm-table__head">
              <span>Test Name</span>
              <span>Result</span>
              <span>Unit</span>
              <span>Reference Range</span>
              <span>Flag</span>
            </div>

            {report.findings.map((f, i) => (
              <div
                key={i}
                className={`rvm-table__row ${f.flag === "H" ? "rvm-table__row--high"
                  : f.flag === "L" ? "rvm-table__row--low" : ""}`}
              >
                <span className="rvm-table__test">{f.test}</span>
                <span className={`rvm-table__result ${
                  f.flag ? "rvm-table__result--flagged" : ""}`}>
                  {f.result}
                </span>
                <span className="rvm-table__unit">{f.unit || "—"}</span>
                <span className="rvm-table__range">{f.range}</span>
                <span className={`rvm-table__flag ${
                  f.flag === "H" ? "rvm-table__flag--h"
                  : f.flag === "L" ? "rvm-table__flag--l"
                  : ""}`}>
                  {f.flag || "—"}
                </span>
              </div>
            ))}
          </div>

          {/* ── Legend ── */}
          <div className="rvm-legend">
            <span className="rvm-legend__item">
              <span className="rvm-legend__dot rvm-legend__dot--red" />
              H = Above normal range
            </span>
            <span className="rvm-legend__item">
              <span className="rvm-legend__dot rvm-legend__dot--blue" />
              L = Below normal range
            </span>
            <span className="rvm-legend__item">
              <span className="rvm-legend__dot rvm-legend__dot--green" />
              — = Within normal limits
            </span>
          </div>

          {/* ── Doctor's Note ── */}
          <div className="rvm-section-title" style={{ marginTop: 20 }}>
            Doctor's Note
          </div>
          <div className="rvm-note">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
              <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="1.8" />
              <path d="M12 8v4m0 4h.01" stroke="currentColor"
                strokeWidth="1.8" strokeLinecap="round" />
            </svg>
            {report.doctorNote}
          </div>

          <p className="rvm-disclaimer">
            * This is a sample lab report for demonstration purposes only.
            Not a real medical document.
          </p>
        </div>
      </div>
    </div>
  );
}